apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  namespace: cleaning-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      containers:
      - name: worker-service
        image: 439891535932.dkr.ecr.us-east-1.amazonaws.com/worker-service:latest
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: cleaning-app
spec:
  selector:
    app: worker-service
  ports:
  - port: 5003
    targetPort: 5003
  type: ClusterIP
