apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-deployer
  namespace: cleaning
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cicd-deployer-role
  namespace: cleaning
rules:
  # core objects
  - apiGroups: [""]
    resources: ["pods","services","configmaps","secrets","endpoints"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  # apps objects
  - apiGroups: ["apps"]
    resources: ["deployments","replicasets"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  # autoscaling
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  # networking
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses","networkpolicies"]
    verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cicd-deployer-binding
  namespace: cleaning
subjects:
  - kind: ServiceAccount
    name: cicd-deployer
    namespace: cleaning
roleRef:
  kind: Role
  name: cicd-deployer-role
  apiGroup: rbac.authorization.k8s.io
